# fly.toml app configuration file generated for codingsimba on 2023-11-14T13:25:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codingsimba"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
