/** @type {import('@remix-run/dev').AppConfig} */
export default {
  browserNodeBuiltinsPolyfill: {
    modules: { punycode: true, stream: true, util: true },
  },
  ignoredRouteFiles: ["**/.*"],
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^bail.*/,
    /^trough.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^decode.*/,
    /^character.*/,
    /^property.*/,
    /^space.*/,
    /^comma.*/,
    /^react-markdown$/,
    /^vfile.*/,
    /^is-plain-obj.*/,
    /^trim-lines.*/,
    /^web-namespaces.*/,
    /^html-void-elements.*/,
    /^zwitch.*/,
    /^lowlight.*/,
    /^devlop.*/,
    /^ccount.*/,
    /^markdown.*/,
    /^longest.*/,
    /^react-icons.*/,
    /^react-syntax-highlighter.*/,
    /^highlight.js.*/,
    /^fault.*/,
    /^format.*/,
  ],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // publicPath: "/build/",
  // serverBuildPath: "build/index.js",
};
