name: Main Blog Build and Deploy

on:
  repository_dispatch:
    types: [content-build]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Content from Content Repository
        run: cp -R ../codingsimba-content/content/posts/* ./content/posts/

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Build and Deploy Blog Content
        run: |
          cd ./content/posts
          npm install
          npm run build
          vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
