name: Build and Deploy Blog Content

on:
  repository_dispatch:
    types: [content-build]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Blog Repository
        uses: actions/checkout@v2
        with:
          repository: christophersesugh/codingsimba # Replace with your main blog repository
          ref: main

      - name: Checkout Content Repository
        uses: actions/checkout@v2
        with:
          repository: christophersesugh/codingsimba-content # Replace with your content repository
          ref: main
          path: content-repo # The directory to checkout the content repository

      - name: List Files in Content Repository
        run: ls -R content-repo

      #   - name: Create Target Directory if Not Exist
      #     run: |
      #       if [ ! -d "./content/posts/" ]; then
      #         mkdir -p ./content/posts/
      #       fi

      - name: Copy Content from Content Repository to Blog Repository
        run: cp -R content-repo/content/posts/* ./codingsimba/content/posts/

      - name: Set Up Node and Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "18.x" # Adjust as needed
      - run: |
          cd codingsimba
          npm install

      - name: Debug Environment Variables
        run: |
          echo "VERCEL_TOKEN: $VERCEL_TOKEN"
          echo "VERCEL_ORG_ID: $VERCEL_ORG_ID"
          echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"

      - name: "Deploy application"
        run: |
          cd codingsimba
          npm vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
