name: Build and Deploy Blog Content

on:
  push:
    paths:
      - "contents/posts/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node and Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - run: npm install

      - name: Debug Environment Variables
        run: |
          echo "VERCEL_TOKEN: $VERCEL_TOKEN"
          echo "VERCEL_ORG_ID: $VERCEL_ORG_ID"
          echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"

      - name: "Deploy application"
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --scope ${{ secrets.VERCEL_ORG_ID }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
