name: Build and Deploy Blog Content

on:
  repository_dispatch:
    types: [content-build]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Content Repository
        uses: actions/checkout@v2
        with:
          repository: christophersesugh/codingsimba-content # Replace with your content repository
          ref: main
          path: content-repo # The directory to checkout the content repository

      - name: List Files in Content Repository
        run: ls -R content-repo

      - name: Create Target Directory if Not Exist
        run: |
          if [ ! -d "./content/posts/" ]; then
            mkdir -p ./content/posts/
          fi

      - name: Copy Content from Content Repository
        run: cp -R content-repo/content/posts/* ./content/posts/

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: "Deploy application"

        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --scope ${{ secrets.VERCEL_ORG_ID }}
        env:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
